version: '3.5'

services:
  jupyter-base:
    image: cyb3rward0g/jupyter-base:0.0.4
    container_name: jupyter-base
    environment:
      JUPYTER_TYPE: notebook
      JUPYTER_BASE_URL: /jupyter
    ports:
      - "8888:8888"
    restart: always
    networks:
      hunting:

networks:
  hunting:
    driver: bridge

volumes:
  notebooks:
    driver: local